# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :build_debug do
    gradle(
        task: "clean assembleDebug",
        print_command: true
    )

    apk_directory = File.expand_path('/Users/jhoanrivers/JhoanPrivate/BayarindTest/apk')

    sh("mkdir -p #{apk_directory}")
    sh("cp /Users/jhoanrivers/JhoanPrivate/BayarindTest/app/build/outputs/apk/debug/app-debug.apk #{apk_directory}")
  
    # sh "your_script.sh"
  end

end
